### PR TITLE
Drawing feature

### PR DESCRIPTION
**Pull request by justinshenk**
Add `hat.ipynb` to examples folder. Should it rather be in `cvloop_examples` notebook?

### CODE REVIEW

**Comment by shoeffner** [comment]
This is an awesome example of how to use it. 

However I would like to reference resources as the example xml for the classifier (e.g. point users to the opencv shared files) rather than including them in the package. Maybe we can find a solution where we don't supply it like this? 

I have in mind providing classes with `__call__` methods for this kind of application, best case would be changing all methods into classes to keep the interface similar everywhere. (See #1 ).

Let's chat about this next week so we can come up with some cool solution!

**Comment by justinshenk** [comment]
Sounds good, yes, it makes sense in the long run. Have a good weekend.

**Comment by shoeffner** [comment]
@JustinShenk as discussed offline I did the following changes:

- Reverted the unnecessary changes to `cvloop/cvloop.py`.
- Converted the code to a class to match the new structure in cvloop.
- Removed the hat images until we have discussed the copyrights.
- Removed the cascade file and added the MacOS default path. #8 will in the future help to make this better.

Additionally I changed the following:
- Only reads one hat file for now, does not choose randomly.
- Reads the cascade only once, during initialization.
- Updated the function example creation script to handle classes properly.
- Moved all parameters as arguments to `DrawHat`'s `__init__`.
- Reverted the version as I only bump that when pushing to master, however I can imagine bumping it on develop already, so maybe when I pull this in I will bump the version as you did.

@JustinShenk , if you find the time after your presentation next week, feel free to review and comment on the changes. I am looking forward to it!

**Comment by justinshenk** [comment]
Looks good, @shoeffner

**Pull request merged**
